trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '10de73b6-42fd-42e1-b36b-95ed7168855b'
  imageRepository: 'medcuritywebappfrontend'
  containerRegistry: 'medcurity.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  s-imageRepository: 'medcuritywebappbackend'
  s-dockerfilePath: '$(Build.SourcesDirectory)/server/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: BuildServer
  displayName: Build and push server
  jobs:
  - job: Build
    displayName: Build Server
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(s-imageRepository)
        dockerfile: $(s-dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)