version: '3.8'

services:
  backend:
    container_name: medcuritywebappbackend
    image: 'medcurity.azurecr.io/medcuritywebappbackend:latest'
    ports:
      - 3002:80
    link: medcuritywebappfrontend
    network: webappnetwork


  frontend:
    container_name: medcuritywebappfrontend
    image: 'medcurity.azurecr.io/medcuritywebappfrontend:latest'
    ports:
      - 80:80
    network: webappnetwork
    depends_on:
      - backend

networks:
  webappnetwork:
     driver: bridge
