version: '3.8'

services:
  backend:
    container_name: medcuritywebappbackend
    image: 'medcurity.azurecr.io/medcuritywebappbackend:latest'
    ports:
      - 80:80


  frontend:
    container_name: medcuritywebappfrontend
    image: 'medcurity.azurecr.io/medcuritywebappfrontend:latest'
    ports:
      - 8080:8080
    depends_on:
      - backend