# This file is used to configure the docker-compose.yml file 
# for local development and Azure deployment.
# THIS FILE CANNOT BE RUN, BUT SECTIONS CAN BE USED

# ------- Local Development Configuration V1 -------
# if in any case the azure service is not available,
# us the version 2
version: '3.8'
services:
  backend:
    container_name: medcuritywebappbackend
    image: 'medcurity.azurecr.io/medcuritywebappbackend'
    restart: always
    build:
      context: server
    command: npm run dev
    ports:
      - 3002:3002
    volumes:
      - ./server/:/code/src:ro
      - ./server/package.json:/code/package.json
      - ./server/package-lock.json:/code/package-lock.json

  frontend:
    container_name: medcuritywebappfrontend
    image: 'medcurity.azurecr.io/medcuritywebappfrontend'
    restart: always
    build:
      context: ./
    ports:
      - 3000:8080
    volumes:
      - ./src:/code/src
      - /code/node_modules
    depends_on:
      - backend

# ------- Local Development Configuration V2 -------
# this case assumes no azure access is available at all
version: '3.8'

services:
  backend:
    build:
      context: server
    command: npm run dev
    ports:
      - 3002:3002
    volumes:
      - ./server/:/code/src:ro
      - ./server/package.json:/code/package.json
      - ./server/package-lock.json:/code/package-lock.json

  frontend:
    build:
      context: ./
    ports:
      - 3000:3000
    volumes:
      - ./src:/code/src
      - /code/node_modules
    depends_on:
      - backend


# ------- Azure Deployment Configuration -------
# this is config for azure deployment
# under deployment center config file
version: '3.8'

services:
  backend:
    container_name: medcuritywebappbackend
    image: 'medcurity.azurecr.io/medcuritywebappbackend:latest'
    ports:
      - 3002:3002

  frontend:
    container_name: medcuritywebappfrontend
    image: 'medcurity.azurecr.io/medcuritywebappfrontend:latest'
    ports:
      - 8080:8080
    depends_on:
      - backend
