name: Azure WebApp Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
     
permissions:
  contents: read

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: medcurity.azurecr.io
        username: medcurity
        password: 8kddBitAYkrsn3aes/n2ahX7tAM7n/+TTD1vvexbyG+ACRA34zJo
    - run: |
        docker build . -t medcurity.azurecr.io/medcuritywebappfrontend:latest
        docker push medcurity.azurecr.io/medcuritywebappfrontend:latest
  build-back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: medcurity.azurecr.io
        username: medcurity
        password: 8kddBitAYkrsn3aes/n2ahX7tAM7n/+TTD1vvexbyG+ACRA34zJo
    - run: |
        cd server
        docker build . -t medcurity.azurecr.io/medcuritywebappbackend:latest
        docker push medcurity.azurecr.io/medcuritywebappbackend:latest

