name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pushing To Another Repo
      run: git init && git remote set-url origin https://github.com/amoltafet/MedcurityApp.git && git add . && git commit -m "g" && git push origin main
